import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>CSS Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-800 flex flex-col">
        <div className="flex flex-col min-h-screen gap-12 items-center py-6">
          <div className="flex flex-col align-center border rounded-lg p-3 bg-gray-700  border-gray-700 min-w-min">
            <div className="flex flex-row text-center">
              <h2 className="text-2xl text-white">CSS Generator</h2>
            </div>

          </div>
          <div className="flex flex-row align-center min-w-min border-2 rounded-lg border-gray-700
            min-h-min p-3 gap-8 items-center sm:w-1/2 md:w-1/3
          ">{/* input text area div  */}
            
              <input type="text
              " className="bg-white-400 h-full w-42 p-1 sm:w-64 md:w-72
                rounded-md border border-gray-50 text-black" placeholder="Describe your layout"
                
               
                />

              <button className="bg-blue-800 h-full min-w-min px-2
                rounded-md border border-gray-50 text-white
              ">Generate</button>
          </div>
          {/* output text area div  */}
          

        </div>
    
      </main>
    </>
  )
}
